export const data = [
  {
    adult: false,
    backdropPath: "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
    genreIds: [878],
    id: 848326,
    originalLanguage: "en",
    originalTitle: "Rebel Moon - Part One: A Child of Fire",
    overview:
      "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
    popularity: 2136.3,
    posterPath:
      "https://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/debris3_blue.png",
    releaseDate: "2023-12-15",
    title: "Rebel Moon - Part One: A Child of Fire",
    video: false,
    voteAverage: 6.4,
    voteCount: 750,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 572802,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/nebula_brown.png",
    releaseDate: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 572801,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/back03.jpg",
    releaseDate: "2015-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 572812,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/back05.jpg",
    releaseDate: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 571802,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/back01.jpg",
    releaseDate: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 272802,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/debris3_blue.png",
    releaseDate: "2010-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 592802,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/nebula_blue.s2014.png",
    releaseDate: "2021-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 572852,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/debris3_blue.png",
    releaseDate: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
  {
    adult: false,
    backdropPath: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genreIds: [28, 12, 14],
    id: 5728222,
    originalLanguage: "en",
    originalTitle: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    posterPath:
      "https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/back01.jpg",
    releaseDate: "2012-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    voteAverage: 6.5,
    voteCount: 299,
  },
];
